// Generated by wxt
// Types for the #import virtual module
declare module '#imports' {
  export { browser, Browser } from 'wxt/browser';
  export { storage, WxtStorage, WxtStorageItem, StorageArea, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage';
  export { getAppConfig, useAppConfig } from 'wxt/utils/app-config';
  export { ContentScriptContext, WxtWindowEventMap } from 'wxt/utils/content-script-context';
  export { createIframeUi, IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe';
  export { createIntegratedUi, IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated';
  export { createShadowRootUi, ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root';
  export { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types';
  export { defineAppConfig, WxtAppConfig } from 'wxt/utils/define-app-config';
  export { defineBackground } from 'wxt/utils/define-background';
  export { defineContentScript } from 'wxt/utils/define-content-script';
  export { defineUnlistedScript } from 'wxt/utils/define-unlisted-script';
  export { defineWxtPlugin } from 'wxt/utils/define-wxt-plugin';
  export { injectScript, ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script';
  export { InvalidMatchPattern, MatchPattern } from 'wxt/utils/match-patterns';
  export { fakeBrowser } from 'wxt/testing';
  export { AIBridge } from '../src/utils/ai-bridge';
  export { commandPalette, createBuiltinCommands, Command } from '../src/utils/command-palette';
  export { byId, assertElement } from '../src/utils/dom-safe';
  export { keyboardManager, createBuiltinShortcuts, KeyboardShortcut } from '../src/utils/keyboard-shortcuts';
  export { PROVIDER_IDS, MODEL_REGISTRY, getGeminiModels, getGeminiDefaultModel, getGeminiModelById } from '../src/utils/model-registry';
  export { alert, confirm, prompt, PnDialog } from '../src/utils/pn-dialog';
  export { recentsAndFavorites, UsageRecord } from '../src/utils/recents-favorites';
  export { searchRanker, SearchableItem, RankedResult } from '../src/utils/search-ranker';
  export { TERMINOLOGY } from '../src/utils/terminology';
  export { toast, Toast } from '../src/utils/toast';
}
