// Generated by wxt
export {}
declare global {
  const AIBridge: typeof import('/Users/shashankmergu/Desktop/promptium/src/utils/ai-bridge').AIBridge
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const MODEL_REGISTRY: typeof import('/Users/shashankmergu/Desktop/promptium/src/utils/model-registry').MODEL_REGISTRY
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const PROVIDER_IDS: typeof import('/Users/shashankmergu/Desktop/promptium/src/utils/model-registry').PROVIDER_IDS
  const assertElement: typeof import('/Users/shashankmergu/Desktop/promptium/src/utils/dom-safe').assertElement
  const browser: typeof import('wxt/browser').browser
  const byId: typeof import('/Users/shashankmergu/Desktop/promptium/src/utils/dom-safe').byId
  const commandPalette: typeof import('/Users/shashankmergu/Desktop/promptium/src/utils/command-palette').commandPalette
  const createBuiltinCommands: typeof import('/Users/shashankmergu/Desktop/promptium/src/utils/command-palette').createBuiltinCommands
  const createBuiltinShortcuts: typeof import('/Users/shashankmergu/Desktop/promptium/src/utils/keyboard-shortcuts').createBuiltinShortcuts
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const fakeBrowser: typeof import('wxt/testing').fakeBrowser
  const getAppConfig: typeof import('wxt/utils/app-config').getAppConfig
  const getGeminiDefaultModel: typeof import('/Users/shashankmergu/Desktop/promptium/src/utils/model-registry').getGeminiDefaultModel
  const getGeminiModelById: typeof import('/Users/shashankmergu/Desktop/promptium/src/utils/model-registry').getGeminiModelById
  const getGeminiModels: typeof import('/Users/shashankmergu/Desktop/promptium/src/utils/model-registry').getGeminiModels
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const keyboardManager: typeof import('/Users/shashankmergu/Desktop/promptium/src/utils/keyboard-shortcuts').keyboardManager
  const recentsAndFavorites: typeof import('/Users/shashankmergu/Desktop/promptium/src/utils/recents-favorites').recentsAndFavorites
  const searchRanker: typeof import('/Users/shashankmergu/Desktop/promptium/src/utils/search-ranker').searchRanker
  const storage: typeof import('wxt/utils/storage').storage
  const toast: typeof import('/Users/shashankmergu/Desktop/promptium/src/utils/toast').toast
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { WxtStorage, WxtStorageItem, StorageArea, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
  // @ts-ignore
  export type { Command } from '/Users/shashankmergu/Desktop/promptium/src/utils/command-palette'
  import('/Users/shashankmergu/Desktop/promptium/src/utils/command-palette')
  // @ts-ignore
  export type { KeyboardShortcut } from '/Users/shashankmergu/Desktop/promptium/src/utils/keyboard-shortcuts'
  import('/Users/shashankmergu/Desktop/promptium/src/utils/keyboard-shortcuts')
  // @ts-ignore
  export type { UsageRecord } from '/Users/shashankmergu/Desktop/promptium/src/utils/recents-favorites'
  import('/Users/shashankmergu/Desktop/promptium/src/utils/recents-favorites')
  // @ts-ignore
  export type { SearchableItem, RankedResult } from '/Users/shashankmergu/Desktop/promptium/src/utils/search-ranker'
  import('/Users/shashankmergu/Desktop/promptium/src/utils/search-ranker')
  // @ts-ignore
  export type { Toast } from '/Users/shashankmergu/Desktop/promptium/src/utils/toast'
  import('/Users/shashankmergu/Desktop/promptium/src/utils/toast')
}
